### PR TITLE
Aggregator demo launch

### PR DESCRIPTION
**Pull request by norro**
Launch setup for a demo on how to use the aggregator.
/cc @Karsten1987 
Signed-off-by: Arne Nordmann <arne.nordmann@de.bosch.com>

### CODE REVIEW

**Comment by Karsten1987** [comment]
@norro Does this address the test failures mentioned [here](https://github.com/ros/diagnostics/pull/118#issuecomment-519280962)?

**Comment by norro** [comment]
Kindof. The demo does the same thing for the parameters that the test also should do. But this doesn't fix the test, yet.
However, I fixed the pluginlib stuff today, so I will be able to have a look at the test tomorrow.

**Comment by Karsten1987** [comment]
Thanks for taking a look on it. Given that you pushed a commit on the `ros2_migrate_diagnostic_aggregator` branch your branch here was to be rebased.

**Comment by norro** [comment]
Superseeded by PR https://github.com/boschresearch/ros2_diagnostics/pull/4.

**Pull request closed without merging**
